spring.datasource.url=jdbc:postgresql://localhost:5432/sports_center_db
spring.datasource.username=postgres
spring.datasource.password=EYUBER200001152015

spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

jwt.secret=ThisIsASecretKeyForSportsCenterProjectThisIsASecretKey
jwt.expiration=86400000